package com.hungerexpress.restaurant;

public enum Cuisine {
    PIZZA, SUSHI, INDIAN, CHINESE, BURGERS, VEGAN, DESSERT, ITALIAN, MEXICAN, AMERICAN, THAI, JAPANESE, KOREAN, MEDITERRANEAN, FRENCH, GREEK, SPANISH, VIETNAMESE
}
